    srv_task_1:
      ansible_host: 192.168.0.111
      ansible_port: 2022
      ansible_user: root
      #I have created a test password to use for the course so I don't have to find ways to hide my credentials. 
      #This way, I can show the full functionality and I can make my life easier as I hardcode the passwd ;)
      ansible_password: Xerxes123 
